ifeq ($(USE_STATIC), y)
PIC=
else
PIC=-fPIC
endif

ifeq ($(USE_PROFILE), y)
PROFILE=-pg
endif

ifeq ($(USE_DEBUG), n)
DEBUG=
else
DEBUG=-g
endif

OPTIMIZE='-DHAVE_SSE -mms-bitfields -mno-cygwin -DDOMAIN -msse -mfpmath=sse,387 -march=pentium3 -O3 -ffast-math -malign-double -pipe -fomit-frame-pointer -mfpmath=387 -m128bit-long-double -minline-all-stringops'

MAKEFLAGS="USE_STATIC=y USE_DEBUG=n"



CC=gcc
CXX=g++
